- name: Nebula Cloud | Release Hostname
  hosts: all
  gather_facts: false
  connection: local
  
  roles:
    - ansible-role-cloudforms-authentication
    - ansible-role-cloudforms-get-vmname
    - ansible-role-release-hostname
