- name: Nebula Cloud | Release Hostname
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
    - name: "Get auth token"
      include_role: 
        name: ansible-role-cloudforms-authentication
    
    - name: "Get All Virtual Machines Connected To A Service"
      include_role: 
        name: ansible-role-cloudforms-get-vmname

    - name: "Release Hostname From Backend"
      include_role: 
        name: ansible-role-release-hostname
      with_items:
        - "{{ service_vms }}"
      loop_control:
        loop_var: vm
