---
# tasks file for ansible-role-reserve-hostname

- name: "Generating Hostname"
  uri:
    url: http://{{ hostname_svc_addr }}:{{ hostname_svc_port }}/hostname/create
    method: POST
    body: >
        {"country":"{{ vm_country }}","infrastructure": "{{ vm_infrastructure }}","os": "{{ vm_os }}"}
    status_code: 201
    body_format: json
    headers:
      Content-Type: "application/json"
  register: inventory_hostname
  ignore_errors: yes

- name: "Generated Hostname"
  debug: var=inventory_hostname.json

- name: "Persisting Hostname"
  set_stats:
    data:
      vm_name: "{{ inventory_hostname.json }}"
